-- ADR-0008 decouples an interest's two roles: scoring vocabulary (every
-- interest, regardless of search terms) and search seed (gap-filler ytsearch
-- queries, only for labels specific enough to search well). Existing rows had
-- their search_terms generated by the old prompt, which produced queries even
-- for broad labels like "AI" or "Running" — polluting the gap-filler.
--
-- A .sql migration cannot call Gemma, so it cannot make the specificity
-- judgement itself. Instead it resets every existing interest's search_terms
-- to a pending sentinel; the startup reconcile (reconcilePendingSearchTerms)
-- re-enqueues generation for each sentinel row, running the new
-- specificity-aware prompt. Broad labels then land on '[]' (vocabulary only),
-- specific ones get fresh terms. The sentinel is not a JSON array, so until a
-- row is reconciled every reader (intake gap-filler, scoring, guard) parses it
-- as "no terms" and skips it for search — safe by default, never emitting a
-- malformed ytsearch query.

UPDATE interests
   SET search_terms = '__pending_specificity__';
